# Setup
title: "Embedded Automotive Insights >>"
description: >
  Explore the promise of embedded technology in the automotive industry
  through concise articles, sharp analysis, and the latest stories on the advancements
  happening in this field.
tagline: "Let's go .."
url: https://sangtdx.github.io
paginate: 5
baseurl: ""
permalink: :title/

kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Optimize Jekyll
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

include: ['_pages'] # customize pages folder
# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-XW85PW7JTE

# Specify the author for blog posts
author:
  name: Tran Dinh Sang
  url: https://www.linkedin.com/in/sangtdx
  email: sang.tran2197@gmail.com

avatar: /assets/img/pikafe.jpg

social:
  name: Sang
  email: sang.tran2197@gmail.com
  twitter: SangTDx
  facebook: SangTDx
  github: SangTDx
  linkedin: SangTDx

timezone : Asia/Ho_Chi_Minh

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/SangTDx